// PersonalFinanceTracker.Frontend/src/components/pages/RegisterPage.tsx
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod"
import {Controller, useForm} from "react-hook-form";
import {Field, FieldError, FieldGroup, FieldLabel} from "../ui/field";
import { Input } from "../ui/input";
import {Button} from "@/components/ui/button.tsx";
import {register} from "@/service/Client.ts";
import {useState} from "react";
import {Alert, AlertDescription, AlertTitle} from "@/components/ui/alert.tsx";
import {Card, CardContent} from "@/components/ui/card.tsx";
import {useNavigate} from "react-router";

export const formSchema = z.object({
    login: z
        .string()
        .min(5, "Логин должен быть больше 5 символов")
        .max(50, "Логин должен быть меньше 50 символов"),
    password: z
        .string()
        .min(5, "Пароль должен быть больше 5 символов")
        .max(50, "Пароль должен быть меньше 50 символов"),
    passwordRepeat: z
        .string()
        .min(5, "Повторение пароля должно быть больше 5 символов")
        .max(50, "Повторение пароля должно быть меньше 50 символов"),
}).refine((data) => data.password === data.passwordRepeat, {
    error: "Пароли должны совпадать",
    path: ["passwordRepeat"]
})

export function RegisterPage() {
    const [isErrorVisible, setIsErrorVisible] = useState<boolean>(false)
    const navigate = useNavigate()

    async function onSubmit(data : z.infer<typeof formSchema>) {
        try {
            await register(data.login, data.password)
            navigate("/login")
        }
        catch (error) {
            console.log(error)
            setIsErrorVisible(true)
        }
    }

    const form = useForm<z.infer<typeof formSchema>>({
        resolver: zodResolver(formSchema),
        defaultValues: {
            login: "",
            password: "",
            passwordRepeat: ""
        }
    })

    return <>
        <div className="flex min-h-screen justify-center items-center">
            <Card className="w-full max-w-sm">
                <CardContent>
                <form onSubmit={form.handleSubmit(onSubmit)}>
                    <FieldGroup>
                        <Controller
                            name="login"
                            control={form.control}
                            render={({ field, fieldState }) => (
                                <Field data-invalid={fieldState.invalid}>
                                    <FieldLabel>Логин</FieldLabel>
                                    <Input value={field.value} onChange={field.onChange} aria-invalid={fieldState.invalid}></Input>
                                    {fieldState.invalid && (
                                        <FieldError errors={[fieldState.error]} />
                                    )}
                                </Field>
                            )}
                        />
                        <Controller
                            name="password"
                            control={form.control}
                            render={({ field, fieldState }) => (
                                <Field data-invalid={fieldState.invalid}>
                                    <FieldLabel>Пароль</FieldLabel>
                                    <Input type="password" value={field.value} onChange={field.onChange} aria-invalid={fieldState.invalid}></Input>
                                    {fieldState.invalid && (
                                        <FieldError errors={[fieldState.error]} />
                                    )}
                                </Field>
                            )}
                        />
                        <Controller
                            name="passwordRepeat"
                            control={form.control}
                            render={({ field, fieldState }) => (
                                <Field data-invalid={fieldState.invalid}>
                                    <FieldLabel>Повторение пароля</FieldLabel>
                                    <Input type="password" value={field.value} onChange={field.onChange} aria-invalid={fieldState.invalid}></Input>
                                    {fieldState.invalid && (
                                        <FieldError errors={[fieldState.error]} />
                                    )}
                                </Field>
                            )}
                        />
                        <Field>
                            <Button type="submit">
                                Зарегистрироваться
                            </Button>
                        </Field>
                        {isErrorVisible && <Alert variant="destructive">
                            <AlertTitle>Ошибка при регистрации!</AlertTitle>
                            <AlertDescription>
                                Регистрация не удалась, попробуйте позже
                            </AlertDescription>
                        </Alert>}
                    </FieldGroup>
                </form>
                </CardContent>
                <Button variant="link">
                    <a href="/login">Аккаунт уже существует?</a>
                </Button>
            </Card>
        </div>
    </>
}

// PersonalFinanceTracker.Frontend/src/pages/RegisterPage.vue
<script setup lang="ts">
import {useAuthStore} from "@/service/AuthStore.ts";
import {register} from "@/service/Client.ts";
import {ref} from "vue";
import {useRouter} from "vue-router";
import {Button} from "@/components/ui/button";
import {Alert, AlertDescription, AlertTitle} from "@/components/ui/alert";
import {Input} from "@/components/ui/input";
import TextField from "@/components/molecules/TextField.vue";

const router = useRouter()
const authStore = useAuthStore()
if (authStore.data != null) {
  router.push("/transactions")
}
const curLogin = ref("")
const curPassword = ref("")
const curPassword2 = ref("")
const curError = ref("")

async function registerButtonClicked() {
  if (curPassword.value != curPassword2.value) {
    curError.value = "Пароли должны совпадать."
    return
  }

  try {
    await register(curLogin.value, curPassword.value);
  }
  catch (error) {
    console.log(error)
    curError.value = "Проверьте корректность логина или пароля. Минимум 5 символов"
    return
  }
  router.push('/login')
}
</script>

<template>
  <div class="flex items-center justify-center min-h-screen flex-col gap-3 px-[40%]">
    <div>Зарегистрироваться</div>
    <TextField title="Логин" v-model="curLogin"></TextField>
    <TextField type="password" title="Пароль" v-model="curPassword"></TextField>
    <TextField type="password" title="Повторите пароль" v-model="curPassword2"></TextField>
    <Button @click="async () => await registerButtonClicked()">Регистрация</Button>
    <Alert variant="destructive" v-if="curError != ''">
      <AlertTitle>Ошибка при входе!</AlertTitle>
      <AlertDescription>
        {{curError}}
      </AlertDescription>
    </Alert>
    <RouterLink to="/login">Уже есть аккаунт?</RouterLink>
  </div>
</template>
